In [30]:
import pandas as pd

In [31]:
df = pd.read_csv("orders.csv")
df.head()
df.tail()

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,Portugal
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,Iran
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,South Korea
39,1040,Anna Ivanova,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,Ukraine

In [32]:
df.info()
df.describe()
# press o to hide and unhide outputs

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OrderID       40 non-null     int64
 1   CustomerName  40 non-null     object
 2   Product       40 non-null     object
 3   Category      40 non-null     object
 4   Quantity      40 non-null     int64
 5   Price         40 non-null     float64
 6   OrderDate     40 non-null     object
 7   Shipped       40 non-null     object
 8   Country       40 non-null     object
dtypes: float64(1), int64(2), object(6)
memory usage: 2.9+ KB

           OrderID    Quantity        Price
count    40.000000   40.000000    40.000000
mean   1020.500000    5.450000   106.457500
std      11.690452   15.903475   201.091854
min    1001.000000    1.000000     0.800000
25%    1010.750000    1.000000    18.000000
50%    1020.500000    1.000000    43.500000
75%    1030.250000    2.250000   112.500000
max    1040.000000  100.000000  1200.000000

In [33]:
print(df.columns, end="\n\n")
print(df.index)

Index(['OrderID', 'CustomerName', 'Product', 'Category', 'Quantity', 'Price',
       'OrderDate', 'Shipped', 'Country'],
      dtype='object')

RangeIndex(start=0, stop=40, step=1)

In [34]:
# df[['Country', 'Product']]
df['Country'] # COLUMN

0              USA
1           Canada
2              UAE
3        Singapore
4           Mexico
5              UAE
6               UK
7      South Korea
8            Italy
9            Japan
10          France
11           India
12       Australia
13           Spain
14           China
15           Egypt
16          Poland
17             USA
18           Japan
19    Saudi Arabia
20          Canada
21          Brazil
22         Germany
23        Pakistan
24          Sweden
25          France
26       Argentina
27          Russia
28     South Korea
29           Italy
30         Morocco
31         Germany
32        Colombia
33             USA
34           Japan
35              UK
36        Portugal
37            Iran
38     South Korea
39         Ukraine
Name: Country, dtype: object

In [35]:
df.iloc[10] # ROW

OrderID                  1011
CustomerName    Sophie Martin
Product                Webcam
Category          Electronics
Quantity                    1
Price                    85.0
OrderDate          2024-06-12
Shipped                   Yes
Country                France
Name: 10, dtype: object

In [36]:
# df[(df['Country'] == 'France') & (df['Product'] == "Webcam")]
# df[df['Country'] == 'France']
# df[(df['Country'] == 'USA') | (df['Product'] == "Webcam")]
df[df['Country'].isin(["USA", "France", "Brazil"])]
# df[~df['Country'].isin(["USA", "France", "Brazil"])]

# ~ inverses the condition and is builtin into pandas

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
10,1011,Sophie Martin,Webcam,Electronics,1,85.0,2024-06-12,Yes,France
17,1018,Michael Brown,Desk Organizer,Furniture,1,65.0,2024-06-19,No,USA
21,1022,Isabella Silva,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,Brazil
25,1026,Chloe Dubois,Paper Shredder,Electronics,1,75.0,2024-06-27,Yes,France
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA

In [37]:
df[df['Quantity'] > 2]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore
5,1006,Nora Ibrahim,Notebook,Stationery,5,5.0,2024-06-07,Yes,UAE
8,1009,Maria Rossi,Pen,Stationery,10,1.5,2024-06-10,Yes,Italy
12,1013,Emma Wilson,Stapler,Stationery,3,12.0,2024-06-14,Yes,Australia
13,1014,Diego Rodriguez,USB Drive,Electronics,5,25.0,2024-06-15,Yes,Spain
15,1016,Ahmed Hassan,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,Egypt
20,1021,David Thompson,Highlighters,Stationery,8,3.5,2024-06-22,No,Canada
23,1024,Zara Ahmed,Sticky Notes,Stationery,15,4.0,2024-06-25,No,Pakistan
27,1028,Nina Petrov,Binder Clips,Stationery,12,2.5,2024-06-29,Yes,Russia
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA

In [38]:
df.loc[df["OrderID"] == 1004]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore

In [39]:
df.loc[df["OrderID"] == 1004, "Quantity"] = 2000
df.loc[df["OrderID"] == 1004]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
3,1004,Alice Wong,Desk Lamp,Furniture,2000,45.0,2024-06-05,Yes,Singapore

In [40]:
df.tail()

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,Portugal
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,Iran
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,South Korea
39,1040,Anna Ivanova,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,Ukraine

In [41]:
df = df.drop(38)
# df = df.dropna() # used to drop NA VALUES
df.fillna({"OrderID": 0}, inplace=True)
df.tail()

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,Japan
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,Portugal
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,Iran
39,1040,Anna Ivanova,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,Ukraine

In [42]:
df.to_csv("new_data.csv", index=False)